---
abstract: 'Mail sending protocol implementation'
author:
  - 'Tom Molesworth <tom@entitymodel.com>'
build_requires:
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::CheckDeps: '0.010'
  Test::More: '0.98'
  perl: '5.010001'
configure_requires:
  ExtUtils::MakeMaker: '6.48'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.014, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Protocol-SMTP
requires:
  Authen::SASL: '0'
  Future: '0.24'
  MIME::Base64: '0'
  curry: '0'
  parent: '0'
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Protocol-SMTP
  homepage: http://search.cpan.org/dist/Protocol-SMTP/
version: '0.001'
